# Generated by Django 4.1.5 on 2023-01-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
